# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0002_auto_20180405_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
