# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0003_userprofile_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
